# Generated by Django 2.1.5 on 2019-03-05 15:00

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('marriage_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=15, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('address', ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('membership', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('head_name', models.CharField(blank=True, max_length=50, null=True)),
                ('exp', models.IntegerField(blank=True, null=True)),
                ('stars', models.IntegerField(blank=True, default=0, null=True)),
                ('suggestions', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shaadi.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', ckeditor.fields.RichTextField(blank=True, max_length=100000, null=True)),
                ('offers', ckeditor.fields.RichTextField(blank=True, max_length=100000, null=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shaadi.Dealer')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shaadi.Customer'),
        ),
        migrations.AddField(
            model_name='book',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shaadi.Dealer'),
        ),
    ]
