# Generated by Django 2.1.5 on 2019-03-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaadi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
