# Generated by Django 2.1.5 on 2019-03-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaadi', '0002_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
